version: '3.1'

services:  
  db:
    image: mysql
    restart: always
    environment:      
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - mysql-db-ss:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:    
    image: server
    build: 
      context: ./server    
    deploy:
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 5
          window: 60s
    environment:      
      - DB_CLIENT=${DB_CLIENT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}    
      - DB_HOST=${DB_HOST}
    ports:
      - ${SRV_PORT}:7878
    expose:
      - ${SRV_PORT}    
    depends_on:
      - db
      - adminer
volumes:
  mysql-db-ss: